### ISSUE TITLE
Accès à la thèse de Nick Lambert

### ISSUE THREAD

**Issue by lenaMK** [rethread-studio/algorithmic-art-course#14]
Je suis à la recherche de la thèse de Nick Lambert:

>   Lambert, Nicholas. “A Critical Examination of Computer Art : Its History and Application.” Thesis (D.Phil.)--University of Oxford, 2003., 2003. Print.

Je l'ai seulement trouvée sur [Bodeleian](https://solo.bodleian.ox.ac.uk/discovery/fulldisplay?docid=alma990155713450107026&context=L&vid=44OXF_INST:SOLO&lang=en&search_scope=MyInst_and_CI&adaptor=Local%20Search%20Engine&tab=Everything&query=creator,contains,nick%20lambert,AND&mode=advanced&pfilter=rtype,exact,dissertations,AND&offset=0). 

Est-ce que quelqu'un a des accès avec cette bibliothèque ou aurais trouvé un autre accès à la thèse?

**Comment by bbaudry** [comment]
https://computer-arts-society.com/casarchive/computerartsthesis/index.html

**Comment by lenaMK** [comment]
c'est parfait merci!
