### ISSUE TITLE
genuary contributions

### ISSUE THREAD

**Issue by bbaudry** [rethread-studio/algorithmic-art-course#17]

**Comment by margelle** [comment]
I'm going to use the prompt:
JAN. 21 Use a library that you haven’t used before.

**Comment by rafpinter** [comment]
I'm working with Bauhaus :)

**Comment by lenaMK** [comment]
Hi, I'll work on [today](https://genuary.art/prompts#jan25)'s prompt

> If you like generative art, you probably have some photos on your phone of cool looking patterns, textures, shapes or things that you’ve seen. You might have even thought, “I should try to recreate this with code”. Today is the day.

**Comment by YBTopaz8** [comment]
I followed the Jan 16th : Draw 10,000 of something.
I tried to illustrate John Horton Conway's Game of Life in C# on both mobile and desktop

https://github.com/YBTopaz8/IFT-6251-GameOfLife

**Comment by bbaudry** [comment]
@margelle : playing with words of a given length, you might like https://www.fxhash.xyz/generative/17668

**Comment by ivanpuhachov** [comment]
I'll post my "grow a seed" soon

**Comment by MdBoisnard** [comment]
Hi! My First draft : https://github.com/MdBoisnard/projets-Cloud2024/blob/main/CloudTest_r%C3%A9ajust%C3%A9Apr%C3%A8sPr%C3%A9sentation.py
;-)

**Comment by bricemichelb** [comment]
I used the prompt Hexagonal of JAN. 10 
https://github.com/bricemichelb/hexagonal

**Comment by siliconfeather** [comment]
Wobbly function: [https://github.com/siliconfeather/algo-art/tree/karlinski]( https://github.com/rafpinter/algorithmic-art/blob/b5eae9f71a61a3cb1f0679e15cda130aac1a3b0a/04-bezier/bezier.js)

**Comment by bbaudry** [comment]
genuary 2024 contributions to the algo art course are done! thanks!
