### ISSUE TITLE
Discord server invite link

### ISSUE THREAD

**Issue by ivanpuhachov** [rethread-studio/algorithmic-art-course#18]
Hi all, here is a discord invitation link - [https://discord.gg/hM288kHb](https://discord.gg/hM288kHb)
Valid for 7 days

**Comment by YBTopaz8** [comment]
Hi Ivan!
Could you please provide a new discord link? Previous one shows as expired.
Thanks

**Comment by ivanpuhachov** [comment]
@YBTopaz8 here you go: https://discord.gg/mMyTm3Bt

**Comment by ivanpuhachov** [comment]
new link: https://discord.gg/cpRG6CWT

**Comment by bbaudry** [comment]
thanks @ivanpuhachov for taking care of this!
