### ISSUE TITLE
github ids for registered students

### ISSUE THREAD

**Issue by bbaudry** [rethread-studio/algorithmic-art-course#19]
please, add your github id here

**Comment by YBTopaz8** [comment]
(Yvan Brunel)[https://github.com/YBTopaz8]

**Comment by YBTopaz8** [comment]
(https://github.com/YBTopaz8)[Yvan Brunel]

**Comment by YBTopaz8** [comment]
My ID would be @YBTopaz8
My Profile: [Yvan Brunel](https://github.com/YBTopaz8)

**Comment by bricemichelb** [comment]
My github id is : bricemichelb

**Comment by margelle** [comment]
Tiffany's github id : @margelle

**Comment by rafpinter** [comment]
Rafaela
@rafpinter

**Comment by lenaMK** [comment]
Lena @lenamk

**Comment by MdBoisnard** [comment]
Maud ID
@MdBoisnard
