### ISSUE TITLE
contributions with an algorithm

### ISSUE THREAD

**Issue by bbaudry** [rethread-studio/algorithmic-art-course#20]
choose an algorithm from [this list](https://github.com/rethread-studio/algorithmic-art-course/issues/11) and make an artwork with it

**Comment by margelle** [comment]
Tiffany's work in progress (WIP) :  https://github.com/margelle/algorithmic-art-tasks/tree/main/task2
Algorithm : L-System https://en.wikipedia.org/wiki/L-system

**Comment by rafpinter** [comment]
Bezier curves: https://github.com/rafpinter/algorithmic-art/blob/main/04-bezier/bezier.js

**Comment by lenaMK** [comment]
Perlin Noise and tiling attempt: https://github.com/lenaMK/art-algorithmique/tree/main/perlin-viz
Tiling and recursing: https://github.com/lenaMK/art-algorithmique/tree/main/tiling

**Comment by siliconfeather** [comment]
Wobbly function: [https://github.com/rafpinter/algorithmic-art/blob/b5eae9f71a61a3cb1f0679e15cda130aac1a3b0a/04-bezier/bezier.js]( https://github.com/siliconfeather/algo-art/tree/karlinski)

**Comment by bricemichelb** [comment]
Hilbert curve :
https://github.com/bricemichelb/hilbertCurve

**Comment by bbaudry** [comment]
@YBTopaz8 @ivanpuhachov can you add a link to your contribution with an algorithm?
thx!

**Comment by YBTopaz8** [comment]
Oh my!
Sorry, here is mine 
https://github.com/YBTopaz8/DataDrivenArt

**Comment by YBTopaz8** [comment]
Oh my!
Sorry, here is mine using recursive arts
https://github.com/YBTopaz8/Recursive-Art

**Comment by MdBoisnard** [comment]
Hello! here it is:
https://github.com/MdBoisnard/projets-Cloud2024

**Comment by ivanpuhachov** [comment]
my nobanana (inspired by marching cubes) - https://github.com/ivanpuhachov/alg-art-works/blob/main/nobanana.py
