### ISSUE TITLE
Cartels

### ISSUE THREAD

**Issue by lenaMK** [rethread-studio/algorithmic-art-course#24]

**Comment by lenaMK** [comment]
I think the max width doesn't work because there are no spaces in our URLs so it doesn't know where to split to go to the next line

**Comment by bbaudry** [comment]
then we can add a white space, or put the name of the repo without subfolders

**Comment by bbaudry** [comment]
added svg export: now, when we click on the canvas, we export an svg

**Comment by bbaudry** [comment]
I also inserted a space in the middle of the url for my code's location and now it's written on 2 lines

**Comment by bbaudry** [comment]
we plotted 6 cartels per A3 sheet, as well as the json data file and the code that generates the plottable cartels
