### ISSUE TITLE
contributions to presentations about research in algorithmic art

### ISSUE THREAD

**Issue by bbaudry** [rethread-studio/algorithmic-art-course#35]

**Comment by margelle** [comment]
Form, Grace and Stark Logic: 30 Years of Algorithmic Drawing
Roman Verostko
October 3, 2009
article (behind paywall) https://doi.org/10.1162/leon.2010.43.3.230

more information:
Author's website http://www.verostko.com/menu.html
Magic Hand of Chance https://www.verostko.com/algorists/theme1b.html
Sayings of Omphalos http://www.verostko.com/epigenet.html
Pathway studio https://www.verostko.com/pathway.html
Cyberflowers https://www.dam.org/archive/verostko/cyberflowers.htm
Twenty-Six Visions of Hildegarde 
https://digitalartarchive.siggraph.org/artwork/roman-verostko-twenty-six-visions-of-hildegarde/
 or 
https://digitalartarchive.at/database/work/1500/

https://en.wikipedia.org/wiki/Hildegard_of_Bingen

something(s) in (his) world that
(he) had never seen before
https://www.wikiart.org/en/jean-arp
https://www.wikiart.org/en/naum-gabo
https://www.artnet.com/artists/antoine-pevsner/

something(s) in my world that
I had never seen before
https://www.wikiart.org/en/remedios-varo
https://www.wikiart.org/en/kay-sage
https://www.wikiart.org/en/vilhelm-hammershoi

**Comment by rafpinter** [comment]
The article that I presented was [Forking a Sketch: How the OpenProcessing Community Uses Remixing to Collect, Annotate, Tune, and Extend Creative Code](https://dl.acm.org/doi/pdf/10.1145/3563657.3595969).

And thanks everyone for the discussions :) let's keep this open-source community active and powerful!

**Comment by siliconfeather** [comment]
The details of the article I presented are:

Title: Artificial Intelligence & Creativity: A Manifesto for Collaboration <https://doi.org/10.1002/jocb.597>

Citation:
Vinchon, F., Lubart, T., Bartolotta, S., Gironnay, V., Botella, M., Bourgeois-Bougrine, S., Burkhardt, J.M., Bonnardel, N., Corazza, G.E., Glăveanu, V. and Hanchett Hanson, M., 2023. Artificial Intelligence & Creativity: A manifesto for collaboration. The Journal of Creative Behavior, 57(4), pp.472-484.

**Comment by lenaMK** [comment]
Bremer, Nadieh, et Shirley Wu. 2021. [Data Sketches](https://www.datasketch.es/)
Went over some details of the [Film flowers write-up and code](https://www.datasketch.es/project/film-flowers)
